name: Clean Orphan Tags

on:
  schedule:
    # 每周一 6:00 UTC 运行
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  runs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予写入权限以删除 Tag

    steps:
      - name: 检查仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: 获取所有 Tag 和 Release
        id: get_tags_releases
        run: |
          # 获取所有 Tag
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ALL_TAGS=$(git tag -l)
          echo "所有 Tag: $ALL_TAGS"

          # 获取所有 Release 关联的 Tag
          RELEASE_TAGS=$(gh api repos/${{ github.repository }}/releases --jq '.[].tag_name' | tr '\n' ' ')
          echo "Release 关联的 Tag: $RELEASE_TAGS"

          # 找出没有 Release 关联的 Tag
          ORPHAN_TAGS=""
          for tag in $ALL_TAGS; do
            if [[ ! " ${RELEASE_TAGS[@]} " =~ " ${tag} " ]]; then
              ORPHAN_TAGS="$ORPHAN_TAGS $tag"
            fi
          done
          echo "需要删除的孤立 Tag: $ORPHAN_TAGS"
          echo "orphan_tags=$ORPHAN_TAGS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 删除孤立 Tag
        if: ${{ steps.get_tags_releases.outputs.orphan_tags != '' }}
        run: |
          ORPHAN_TAGS="${{ steps.get_tags_releases.outputs.orphan_tags }}"
          for tag in $ORPHAN_TAGS; do
            echo "正在删除 Tag: $tag"
            git push origin --delete "$tag"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 需要写入权限
